env:
  config_file: ./scenarios/defend_the_center.cfg
  variables:
    - kills
    - ammo
    - health
  train:
    show: False
    advance_steps: 10
    sound: False
  play:
    show: True
    advance_steps: 1
    sound: True

hiperparams:
  input_shape: (64, 64, 10)
  lr: 0.0001
  gamma: 0.99
  batch_size: 32
  train_freq: 100
  update_target_model_freq: 3000
  memory_size: 20000
  epsilon:
    initial: 1.0
    final: 0.001
  phase_time:
    observe: 20000
    explore: 100000

checkpoint:
  freq: 5000
  path: checkpoints

metric:
  path: ./metrics

logger:
  name: agent
  path: logs
  level: INFO
  message_format: "%(levelname)s %(asctime)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
