env:
  config_file: ./scenarios/defend_the_center.cfg
  variables:
    - kills
    - ammo
    - health
  show: False

net:
  input_shape: (64, 64, 10)

train:
  lr: 0.0001
  gamma: 0.99
  batch_size: 32
  freq: 100
  checkpoint:
    monitor: loss
    path: ./checkpoints
  update_target_model_freq: 3000

memory_size: 20000

epsilon:
  initial: 1.0
  final: 0.001

phase_time:
  observe: 5000
  explore: 50000

metrics:
  path: ./metrics

logger:
  name: agent
  path: logs
  level: INFO
  message_format: "%(levelname)s %(asctime)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
