#!/bin/bash
# ======================================================================================================================
# Params
# ======================================================================================================================
SHELL_CONFIG_FILE=".$1rc"
echo "Shell: $1"

if [ "$2" == "gpu" ]
then
    echo "Use: $2"
    SUDO="sudo"
    USE_GPU="$SUDO systemctl start bumblebeed; $SUDO optiprime"
fi
DEFAULT_SCENE_PATH=scenarios/defend_the_center


# ======================================================================================================================
# Commands
# ======================================================================================================================
ENV_ACTIVATE="conda activate doom-agent"
REMOVE_TRAIN_FILES="$SUDO rm -rf logs metrics checkpoints"
TRAIN="$ENV_ACTIVATE; $USE_GPU python agent-train.py"
PLAY="$ENV_ACTIVATE; $USE_GPU python agent-play.py"
DEMO="$PLAY --config $DEFAULT_SCENE_PATH/agent.yml --weights $DEFAULT_SCENE_PATH/2019_02_09_17_19_52-weights-loss_0.0123.h5"
REPORT="$ENV_ACTIVATE; python report.py"
TENSOR_BOARD="$ENV_ACTIVATE; tensorboard --logdir metrics"
# ======================================================================================================================


# ======================================================================================================================
# Functions
# ======================================================================================================================
function write()     { echo -e $1 >> ~/$SHELL_CONFIG_FILE; }
function separator() { write "# ===================================================================================="; }
function header()    { write  ""; separator; write "# $1"; separator; }


# ======================================================================================================================
# Main
# ======================================================================================================================
header "doom-agent config"
write 'export PATH=.:$PATH'
write "# Shortcuts..."
write "alias agent-train='$REMOVE_TRAIN_FILES; $TRAIN'"
write "alias agent-play='$PLAY'"
write "alias agent-demo='$DEMO'"
write "alias agent-report='$REPORT'"
write "alias agent-metrics='$TENSOR_BOARD'"
separator
